name: Build and Deploy
on:
  push:
    branches:
      - dev
    paths:
      - 'host/**' 
      - 'echarts/**' 
      - '.github/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18


      - name: Install and Build
        run: |
          cd host
          rm -rf node_modules pnpm-lock.yaml
          npm i -g pnpm
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          publish_dir: ./host
          destination_dir: ./host
          keep_files: true  # 保留已有文件